/* eslint-disable quotes, quote-props, comma-dangle, max-len */
export default {
  "config": {
    "appName": "este",
    "appVersion": "8ddac36add3a65aed403abc049bcdea8b6b524c0",
    "firebase": {
      "apiKey": "AIzaSyDZRAOrDErAaC-TCKbr4cMzaohsPR4sWgU",
      "authDomain": "este.firebaseapp.com",
      "databaseURL": "https://este.firebaseio.com",
      "storageBucket": "project-808488257248094054.appspot.com"
    },
    "sentryUrl": "https://f297cec9c9654088b8ccf1ea9136c458@app.getsentry.com/77415"
  },
  "device": {
    "host": "",
    "isReactNative": false,
    "platform": ""
  },
  "intl": {
    "currentLocale": "en",
    "defaultLocale": "en",
    "initialNow": null,
    "locales": [
      "cs",
      "de",
      "en",
      "es",
      "fr",
      "pt",
      "ro"
    ],
    "messages": {
      "cs": {
        "app.buttons.add": "Přidat",
        "app.buttons.cancel": "Zrušit",
        "app.buttons.delete": "Smazat",
        "app.buttons.dismiss": "Zrušit",
        "app.buttons.edit": "Editovat",
        "app.buttons.save": "Uložit",
        "app.buttons.signIn": "Přihlášení",
        "app.buttons.signOut": "Odhlásit se",
        "app.buttons.signUp": "Registrace",
        "app.buttons.submit": "Odeslat",
        "app.confirm.areYouSure": "Jste si jistý?",
        "app.confirm.unsavedChanges": "Máte neuložené změny. Jste si jistý?",
        "app.links.fields": "Fields",
        "app.links.home": "Úvod",
        "app.links.intl": "Lokalizace",
        "app.links.me": "Já",
        "app.links.notFound": "Stránka nenalezena",
        "app.links.offline": "Offline",
        "app.links.profile": "Profil",
        "app.links.settings": "Nastavení",
        "app.links.signIn": "Přihlášení",
        "app.links.todos": "Úkoly",
        "app.links.users": "Uživatelé",
        "auth.email.emailLegend": "Email",
        "auth.email.emailPlaceholder": "tvuj@email.com",
        "auth.email.passwordForgotten": "Zapomenuté heslo",
        "auth.email.passwordPlaceholder": "heslo",
        "auth.email.passwordRecoveryLegend": "Obnovení hesla",
        "auth.email.recoveryEmailSent": "Email pro obnovení hesla odeslán.",
        "auth.email.resetPassword": "Reset hesla",
        "auth.signInError.email": "Emailová adresa není správná.",
        "auth.signInError.required": "Prosím vyplňte {prop, select, email {email} password {heslo}}.",
        "auth.signInError.simplePassword": "Heslo musí obsahovat alespoň {minLength} znaků.",
        "auth.social.facebookSignIn": "Přihlášení přes Facebook",
        "firebase.error.EMAIL_TAKEN": "Tento email je už obsazen.",
        "firebase.error.INVALID_EMAIL": "Email není ve správném formátu.",
        "firebase.error.INVALID_PASSWORD": "Nesprávné heslo.",
        "firebase.error.INVALID_USER": "Nesprávný uživatel.",
        "footer.madeByHtml": "stvořil",
        "intl.page.unreadCount": "{unreadCount, plural, one {zpráva} other {zpráv}}",
        "loading.loadingText": "Nahrávám",
        "loading.longLoadingText": "Stále nahrávám...",
        "notFound.continue": "Pokračujte zde prosím.",
        "notFound.h1": "Tato stránka není dostupná",
        "notFound.p": "Možná máte špatný odkaz, nebo byla stránka odstraněna.",
        "todos.buttons.add100": "Přidat 100 úkolů",
        "todos.buttons.clearAll": "Vymazat vše",
        "todos.buttons.clearCompleted": "Vymazat hotové",
        "todos.leftTodos": "{leftTodos, plural, =0 {Nic, užívej :-)} one {Máš {leftTodos} úkol} other {Máš {leftTodos} úkolů}}",
        "todos.newTodo.placeholder": "Co je třeba udělat?",
        "todos.todos.empty": "Nic tu není..."
      },
      "de": {
        "app.buttons.add": "Hinzufügen",
        "app.buttons.cancel": "Abbrechen",
        "app.buttons.delete": "Löschen",
        "app.buttons.dismiss": "Entlassen",
        "app.buttons.edit": "Bearbeiten",
        "app.buttons.save": "Speichern",
        "app.buttons.signIn": "Anmelden",
        "app.buttons.signOut": "Abmelden",
        "app.buttons.signUp": "Anmelden",
        "app.buttons.submit": "Senden",
        "app.confirm.areYouSure": "Sind Sie sicher?",
        "app.confirm.unsavedChanges": "Sie haben Änderungen gemacht. Sind Sie sicher?",
        "app.links.fields": "Fields",
        "app.links.home": "Homepage",
        "app.links.intl": "Übersetzung",
        "app.links.me": "Ich",
        "app.links.notFound": "Seite nicht gefunden",
        "app.links.offline": "Offline",
        "app.links.profile": "Profil",
        "app.links.settings": "Einstellungen",
        "app.links.signIn": "Anmelden",
        "app.links.todos": "Aufgaben",
        "app.links.users": "Benutzer",
        "auth.email.emailLegend": "E-Mail",
        "auth.email.emailPlaceholder": "ihre@email.com",
        "auth.email.passwordForgotten": "Passwort vergessen?",
        "auth.email.passwordPlaceholder": "Passwort",
        "auth.email.passwordRecoveryLegend": "Passwort zurücksetzen",
        "auth.email.recoveryEmailSent": "Die E-Mail zum Zurücksetzen Ihres Passwortes wurde gesendet.",
        "auth.email.resetPassword": "Passwort zurücksetzen",
        "auth.signInError.email": "Diese E-Mail Adresse ist nicht gültig.",
        "auth.signInError.required": "Bitte füllen Sie das Feld {prop, select, email {Email} password {Passwort}} aus.",
        "auth.signInError.simplePassword": "Das Passwort muss mindestens {minLength} Zeichen lang sein.",
        "auth.social.facebookSignIn": "Anmeldung via Facebook",
        "firebase.error.EMAIL_TAKEN": "Das Konto konnte nicht erstellt werden, weil die E-Mail bereits benutzt wurde.",
        "firebase.error.INVALID_EMAIL": "Die angegebene E-Mail ist nicht gültig.",
        "firebase.error.INVALID_PASSWORD": "Das eingegebene Passwort ist falsch für dieses Konto.",
        "firebase.error.INVALID_USER": "Das eigegebene Konto existiert nicht.",
        "footer.madeByHtml": "Umgesetzt von",
        "intl.page.unreadCount": "{unreadCount, plural, one {Meldung} other {Meldungen}}",
        "loading.loadingText": "Laden",
        "loading.longLoadingText": "Noch Laden, überprüfen Sie bitte Ihre Verbindung",
        "notFound.continue": "Hier weiter bitte",
        "notFound.h1": "Diese Seite existiert nicht.",
        "notFound.p": "Der Link ist möglicherweise veraltet oder die Seite wurde gelöscht.",
        "todos.buttons.add100": "100 Aufgaben hinzufügen",
        "todos.buttons.clearAll": "Alles löschen",
        "todos.buttons.clearCompleted": "Löschen abgeschlossen",
        "todos.leftTodos": "{leftTodos, plural, =0 {Es gibt nichts mehr zu tun, viel Spass! :-)} one {Sie haben {leftTodos} Aufgabe} other {Sie haben {leftTodos} Aufgaben}}",
        "todos.newTodo.placeholder": "Was müssen Sie tun?",
        "todos.todos.empty": "Es ist eher ruhig hier..."
      },
      "es": {
        "app.buttons.add": "Añadir",
        "app.buttons.cancel": "Cancelar",
        "app.buttons.delete": "Borrar",
        "app.buttons.dismiss": "Despedir",
        "app.buttons.edit": "Editar",
        "app.buttons.save": "Salvar",
        "app.buttons.signIn": "Iniciar Sesión",
        "app.buttons.signOut": "Cerrar Sesión",
        "app.buttons.signUp": "Regístrate",
        "app.buttons.submit": "Enviar",
        "app.confirm.areYouSure": "¿Estás seguro?",
        "app.confirm.unsavedChanges": "Hay cambios sin guardar. ¿Estás seguro?",
        "app.links.fields": "Campos",
        "app.links.home": "Inicio",
        "app.links.intl": "Idioma",
        "app.links.me": "Yo",
        "app.links.notFound": "Página no encontrada",
        "app.links.offline": "Desconectado",
        "app.links.profile": "Perfil",
        "app.links.settings": "Ajustes",
        "app.links.signIn": "Iniciar Sesión",
        "app.links.todos": "Tareas",
        "app.links.users": "Usuarios",
        "auth.email.emailLegend": "Correo",
        "auth.email.emailPlaceholder": "tu@email.com",
        "auth.email.passwordForgotten": "Olvido su contraseña?",
        "auth.email.passwordPlaceholder": "contraseña",
        "auth.email.passwordRecoveryLegend": "Recuperación de contraseña de correo electrónico.",
        "auth.email.recoveryEmailSent": "Correo electrónico de recuperación ha sido enviado.",
        "auth.email.resetPassword": "Restablecer contraseña",
        "auth.signInError.email": "Dirección de correo no valida.",
        "auth.signInError.required": "Por favor llenar {prop, select, email {email} password {contraseña}}.",
        "auth.signInError.simplePassword": "La contraseña debe contener al menos {minLength} caracteres.",
        "auth.social.facebookSignIn": "Iniciar sesión en Facebook",
        "firebase.error.EMAIL_TAKEN": "La nueva cuenta de usuario no puede ser creada porque la dirección de correo electrónico especificada ya se encuentra en uso.",
        "firebase.error.INVALID_EMAIL": "La dirección de correo especificada no es una dirección de correo válida.",
        "firebase.error.INVALID_PASSWORD": "La contraseña de la cuenta de usuario especificada no es válida.",
        "firebase.error.INVALID_USER": "La cuenta de usuario especificada no existe.",
        "footer.madeByHtml": "Hecho por",
        "intl.page.unreadCount": "{unreadCount, plural, one {mensaje} other {mensajes}}",
        "loading.loadingText": "Cargando",
        "loading.longLoadingText": "Todavía se está cargando, por favor, compruebe su conexión",
        "notFound.continue": "Continuar aquí por favor.",
        "notFound.h1": "Esta página no está disponible",
        "notFound.p": "El link puede estar roto, o la página ha sido eliminada.",
        "todos.buttons.add100": "Adicionar 100 Tareas",
        "todos.buttons.clearAll": "Borrar Tareas",
        "todos.buttons.clearCompleted": "Borrado Completo",
        "todos.leftTodos": "{leftTodos, plural, =0 {Nada, Disfruta :-)} one {Usted tiene {leftTodos} tareas} other {Usted tiene {leftTodos} tareas}}",
        "todos.newTodo.placeholder": "Que hay que hacer?",
        "todos.todos.empty": "Esta bastante vacío aquí..."
      },
      "fr": {
        "app.buttons.add": "Ajouter",
        "app.buttons.cancel": "Annuler",
        "app.buttons.delete": "Supprimer",
        "app.buttons.dismiss": "Rejeter",
        "app.buttons.edit": "Editer",
        "app.buttons.save": "Enregistrer",
        "app.buttons.signIn": "Connexion",
        "app.buttons.signOut": "Déconnexion",
        "app.buttons.signUp": "S'inscrire",
        "app.buttons.submit": "Envoyer",
        "app.confirm.areYouSure": "Etes-vous sûr ?",
        "app.confirm.unsavedChanges": "Vous avez effectué des modifications. Etes-vous sûr ?",
        "app.links.fields": "Fields",
        "app.links.home": "Accueil",
        "app.links.intl": "Traduction",
        "app.links.me": "Moi",
        "app.links.notFound": "Page introuvable",
        "app.links.offline": "Hors ligne",
        "app.links.profile": "Profil",
        "app.links.settings": "Paramètres",
        "app.links.signIn": "Connexion",
        "app.links.todos": "Tâches",
        "app.links.users": "Utilisateurs",
        "auth.email.emailLegend": "Email",
        "auth.email.emailPlaceholder": "votre@email.com",
        "auth.email.passwordForgotten": "Mot de passe oublié ?",
        "auth.email.passwordPlaceholder": "mot de passe",
        "auth.email.passwordRecoveryLegend": "Récupération de mot de passe",
        "auth.email.recoveryEmailSent": "L'email de récupération du mot de passe a été envoyé.",
        "auth.email.resetPassword": "Réinitialiser le mot de passe",
        "auth.signInError.email": "L'adresse email n'est pas valide.",
        "auth.signInError.required": "Veuillez remplir le champ {prop, select, email {email} password {mot de passe}}.",
        "auth.signInError.simplePassword": "Le mot de passe doit contenir au moins {minLength} caractères.",
        "auth.social.facebookSignIn": "Connexion Facebook",
        "firebase.error.EMAIL_TAKEN": "Le nouveau compte utilisateur ne peut pas être créé car l'email indiqué est déjà utilisé.",
        "firebase.error.INVALID_EMAIL": "L'email spécifié n'est pas valide.",
        "firebase.error.INVALID_PASSWORD": "Le mot de passe du compte utilisateur spécifié est incorrect.",
        "firebase.error.INVALID_USER": "Le compte utilisateur spécifié n'existe pas.",
        "footer.madeByHtml": "Réalisé avec amour par",
        "intl.page.unreadCount": "{unreadCount, plural, one {message} other {messages}}",
        "loading.loadingText": "Chargement",
        "loading.longLoadingText": "Chargement toujours, s'il vous plaît vérifier votre connexion",
        "notFound.continue": "Continuez ici s'il vous plaît.",
        "notFound.h1": "Cette page n'est pas disponible",
        "notFound.p": "Le lien est peut-être périmé ou la page a été supprimée.",
        "todos.buttons.add100": "Ajouter 100 tâches",
        "todos.buttons.clearAll": "Tout supprimer",
        "todos.buttons.clearCompleted": "Suppression terminée",
        "todos.leftTodos": "{leftTodos, plural, =0 {Il n'y a rien à faire, profitez ! :-)} one {Vous avez {leftTodos} tâche} other {Vous avez {leftTodos} tâches}}",
        "todos.newTodo.placeholder": "Qu'avez-vous à faire ?",
        "todos.todos.empty": "C'est plutôt calme par ici..."
      },
      "pt": {
        "app.buttons.add": "Adicionar",
        "app.buttons.cancel": "Cancelar",
        "app.buttons.delete": "Excluir",
        "app.buttons.dismiss": "Demitir",
        "app.buttons.edit": "Editar",
        "app.buttons.save": "Salvar",
        "app.buttons.signIn": "Usuário",
        "app.buttons.signOut": "Sair",
        "app.buttons.signUp": "Inscrever-se",
        "app.buttons.submit": "Enviar",
        "app.confirm.areYouSure": "Você tem certeza?",
        "app.confirm.unsavedChanges": "Você tem alterações não salvas. Você tem certeza?",
        "app.links.fields": "Campos",
        "app.links.home": "Início",
        "app.links.intl": "Idioma",
        "app.links.me": "Eu",
        "app.links.notFound": "Página não encontrada",
        "app.links.offline": "Off-line",
        "app.links.profile": "Perfil",
        "app.links.settings": "Configurações",
        "app.links.signIn": "Usuário",
        "app.links.todos": "Tarefas",
        "app.links.users": "Usuários",
        "auth.email.emailLegend": "Email",
        "auth.email.emailPlaceholder": "endereço@email.com",
        "auth.email.passwordForgotten": "Esqueceu sua senha?",
        "auth.email.passwordPlaceholder": "senha",
        "auth.email.passwordRecoveryLegend": "Email para recuperação de senha.",
        "auth.email.recoveryEmailSent": "Email de recuperação foi enviado.",
        "auth.email.resetPassword": "Restaurar Senha",
        "auth.signInError.email": "Email inválido.",
        "auth.signInError.required": "Favor preencher {prop, select, email {endereço de email} password {senha}}.",
        "auth.signInError.simplePassword": "Senha precisa conter {minLength} caracteres.",
        "auth.social.facebookSignIn": "Login do Facebook",
        "firebase.error.EMAIL_TAKEN": "Novo usuário não pode ser criado, o email informado já foi utilizado.",
        "firebase.error.INVALID_EMAIL": "Email informado não é válido.",
        "firebase.error.INVALID_PASSWORD": "A senha do usuário específico está incorreta.",
        "firebase.error.INVALID_USER": "Usuário especificado não existe.",
        "footer.madeByHtml": "desenvolvido por",
        "intl.page.unreadCount": "{unreadCount, plural, one {mensagem} other {mensagens}}",
        "loading.loadingText": "Carregando",
        "loading.longLoadingText": "Ainda a carregar, por favor, verifique sua conexão",
        "notFound.continue": "Por favor, continue aqui.",
        "notFound.h1": "A página não está disponível",
        "notFound.p": "O link está indisponível ou a página foi removida.",
        "todos.buttons.add100": "Adicionar 100 Tarefas",
        "todos.buttons.clearAll": "Apagar Tudo",
        "todos.buttons.clearCompleted": "Limpeza Completa",
        "todos.leftTodos": "{leftTodos, plural, =0 {Não tarefas pendentes, apreciar :-)} one {Você tem {leftTodos} tarefa} other {Você tem {leftTodos} tarefas}}",
        "todos.newTodo.placeholder": "O que precisa ser feito?",
        "todos.todos.empty": "Vazio..."
      },
      "ro": {
        "app.buttons.add": "Adăuga",
        "app.buttons.cancel": "Anulare",
        "app.buttons.delete": "Șterge",
        "app.buttons.dismiss": "Destitui",
        "app.buttons.edit": "Editați",
        "app.buttons.save": "Salvați",
        "app.buttons.signIn": "Autentificare",
        "app.buttons.signOut": "Deconectare",
        "app.buttons.signUp": "Inscrie-te",
        "app.buttons.submit": "A depune",
        "app.confirm.areYouSure": "Esti sigur?",
        "app.confirm.unsavedChanges": "Ai modificări nesalvate. Esti sigur?",
        "app.links.fields": "Câmpuri",
        "app.links.home": "Acasă",
        "app.links.intl": "Traducere",
        "app.links.me": "Eu",
        "app.links.notFound": "Pagina nu poate fi găsită",
        "app.links.offline": "Deconectat",
        "app.links.profile": "Profil",
        "app.links.settings": "Parametri",
        "app.links.signIn": "Autentificare",
        "app.links.todos": "Tasks",
        "app.links.users": "Utilizatori",
        "auth.email.emailLegend": "E-mail",
        "auth.email.emailPlaceholder": "altău@email.com",
        "auth.email.passwordForgotten": "Ai uitat parola?",
        "auth.email.passwordPlaceholder": "Parolă",
        "auth.email.passwordRecoveryLegend": "Recuperarea parolei de email",
        "auth.email.recoveryEmailSent": "Emailul de recuperare a fost trimis.",
        "auth.email.resetPassword": "Resetează parola",
        "auth.signInError.email": "Adresa e-mail nu este validă.",
        "auth.signInError.required": "Completați câmpurile {prop, select, email {email} password {parolă}}.",
        "auth.signInError.simplePassword": "Parola trebuie să conține cel puțin {minLength} caractere.",
        "auth.social.facebookSignIn": "Logare Facebook",
        "firebase.error.EMAIL_TAKEN": "Noul cont de utilizator nu poate fi creat, deoarece adresa de email specificată este deja în uz.",
        "firebase.error.INVALID_EMAIL": "Emailul specificat nu este un email valid.",
        "firebase.error.INVALID_PASSWORD": "Parola specificată contului de utilizator este incorectă.",
        "firebase.error.INVALID_USER": "Contul de utilizator specificat nu există.",
        "footer.madeByHtml": "realizat de",
        "intl.page.unreadCount": "{unreadCount, plural, one {mesaj} other {mesaje}}",
        "loading.loadingText": "Se incarca",
        "loading.longLoadingText": "Încă se încarcă, vă rugăm să verificați conexiunea",
        "notFound.continue": "Continuați aici, vă rog.",
        "notFound.h1": "Această pagină nu este disponibilă",
        "notFound.p": "S-ar putea că linkul a fost vechi sau că pagina a fost ștearsă.",
        "todos.buttons.add100": "Adăugați 100 de sarcini.",
        "todos.buttons.clearAll": "Șterge totul",
        "todos.buttons.clearCompleted": "Ștergere reușită",
        "todos.leftTodos": "{leftTodos, plural, =0 {Nu e nimic de făcut! :-)} one {Aveți o sarcină} other {Aveți {leftTodos} sarcini}}",
        "todos.newTodo.placeholder": "Ce trebuie să faceți ?",
        "todos.todos.empty": "E calm pe aici..."
      }
    }
  }
};
