/* eslint-disable quotes, quote-props, comma-dangle, max-len */
export default {
  config: {
    appName: 'este',
    firebase: {
      apiKey: 'AIzaSyDZRAOrDErAaC-TCKbr4cMzaohsPR4sWgU',
      authDomain: 'este.firebaseapp.com',
      databaseURL: 'https://este.firebaseio.com',
      storageBucket: 'project-808488257248094054.appspot.com',
    },
    sentryUrl: 'https://f297cec9c9654088b8ccf1ea9136c458@app.getsentry.com/77415',
  },
  device: {
    host: '',
    isReactNative: false,
    platform: '',
  },
  intl: {
    currentLocale: 'es',
    defaultLocale: 'en',
    initialNow: null,
    locales: ['en', 'es', 'fr'],
    messages: {
      es: {
        'app.buttons.add': 'Añadir',
        'app.buttons.cancel': 'Cancelar',
        'app.buttons.delete': 'Borrar',
        'app.buttons.dismiss': 'Despedir',
        'app.buttons.edit': 'Editar',
        'app.buttons.save': 'Salvar',
        'app.buttons.signIn': 'Iniciar Sesión',
        'app.buttons.signOut': 'Cerrar Sesión',
        'app.buttons.signUp': 'Regístrate',
        'app.buttons.submit': 'Enviar',
        'app.confirm.areYouSure': '¿Estás seguro?',
        'app.confirm.unsavedChanges': 'Hay cambios sin guardar. ¿Estás seguro?',
        'app.links.fields': 'Campos',
        'app.links.home': 'Inicio',
        'app.links.intl': 'Idioma',
        'app.links.me': 'Yo',
        'app.links.notFound': 'Página no encontrada',
        'app.links.offline': 'Desconectado',
        'app.links.profile': 'Perfil',
        'app.links.settings': 'Ajustes',
        'app.links.signIn': 'Iniciar Sesión',
        'app.links.todos': 'Tareas',
        'app.links.users': 'Usuarios',
        'auth.email.emailLegend': 'Correo',
        'auth.email.emailPlaceholder': 'tu@email.com',
        'auth.email.passwordForgotten': 'Olvido su contraseña?',
        'auth.email.passwordPlaceholder': 'contraseña',
        'auth.email.passwordRecoveryLegend': 'Recuperación de contraseña de correo electrónico.',
        'auth.email.recoveryEmailSent': 'Correo electrónico de recuperación ha sido enviado.',
        'auth.email.resetPassword': 'Restablecer contraseña',
        'auth.signInError.email': 'Dirección de correo no valida.',
        'auth.signInError.required':
          'Por favor llenar {prop, select, email {email} password {contraseña}}.',
        'auth.signInError.simplePassword':
          'La contraseña debe contener al menos {minLength} caracteres.',
        'auth.social.facebookSignIn': 'Iniciar sesión en Facebook',
        'firebase.error.EMAIL_TAKEN':
          'La nueva cuenta de usuario no puede ser creada porque la dirección de correo electrónico especificada ya se encuentra en uso.',
        'firebase.error.INVALID_EMAIL':
          'La dirección de correo especificada no es una dirección de correo válida.',
        'firebase.error.INVALID_PASSWORD':
          'La contraseña de la cuenta de usuario especificada no es válida.',
        'firebase.error.INVALID_USER': 'La cuenta de usuario especificada no existe.',
        'footer.madeByHtml': 'Hecho por',
        'intl.page.unreadCount': '{unreadCount, plural, one {mensaje} other {mensajes}}',
        'loading.loadingText': 'Cargando',
        'loading.longLoadingText': 'Todavía se está cargando, por favor, compruebe su conexión',
        'notFound.continue': 'Continuar aquí por favor.',
        'notFound.h1': 'Esta página no está disponible',
        'notFound.p': 'El link puede estar roto, o la página ha sido eliminada.',
        'todos.buttons.add100': 'Adicionar 100 Tareas',
        'todos.buttons.clearAll': 'Borrar Tareas',
        'todos.buttons.clearCompleted': 'Borrado Completo',
        'todos.leftTodos':
          '{leftTodos, plural, =0 {Nada, Disfruta :-)} one {Usted tiene {leftTodos} tareas} other {Usted tiene {leftTodos} tareas}}',
        'todos.newTodo.placeholder': 'Que hay que hacer?',
        'todos.todos.empty': 'Esta bastante vacío aquí...',
      },
      fr: {
        'app.buttons.add': 'Ajouter',
        'app.buttons.cancel': 'Annuler',
        'app.buttons.delete': 'Supprimer',
        'app.buttons.dismiss': 'Rejeter',
        'app.buttons.edit': 'Editer',
        'app.buttons.save': 'Enregistrer',
        'app.buttons.signIn': 'Connexion',
        'app.buttons.signOut': 'Déconnexion',
        'app.buttons.signUp': "S'inscrire",
        'app.buttons.submit': 'Envoyer',
        'app.confirm.areYouSure': 'Etes-vous sûr ?',
        'app.confirm.unsavedChanges': 'Vous avez effectué des modifications. Etes-vous sûr ?',
        'app.links.fields': 'Fields',
        'app.links.home': 'Accueil',
        'app.links.intl': 'Traduction',
        'app.links.me': 'Moi',
        'app.links.notFound': 'Page introuvable',
        'app.links.offline': 'Hors ligne',
        'app.links.profile': 'Profil',
        'app.links.settings': 'Paramètres',
        'app.links.signIn': 'Connexion',
        'app.links.todos': 'Tâches',
        'app.links.users': 'Utilisateurs',
        'auth.email.emailLegend': 'Email',
        'auth.email.emailPlaceholder': 'votre@email.com',
        'auth.email.passwordForgotten': 'Mot de passe oublié ?',
        'auth.email.passwordPlaceholder': 'mot de passe',
        'auth.email.passwordRecoveryLegend': 'Récupération de mot de passe',
        'auth.email.recoveryEmailSent': "L'email de récupération du mot de passe a été envoyé.",
        'auth.email.resetPassword': 'Réinitialiser le mot de passe',
        'auth.signInError.email': "L'adresse email n'est pas valide.",
        'auth.signInError.required':
          'Veuillez remplir le champ {prop, select, email {email} password {mot de passe}}.',
        'auth.signInError.simplePassword':
          'Le mot de passe doit contenir au moins {minLength} caractères.',
        'auth.social.facebookSignIn': 'Connexion Facebook',
        'firebase.error.EMAIL_TAKEN':
          "Le nouveau compte utilisateur ne peut pas être créé car l'email indiqué est déjà utilisé.",
        'firebase.error.INVALID_EMAIL': "L'email spécifié n'est pas valide.",
        'firebase.error.INVALID_PASSWORD':
          'Le mot de passe du compte utilisateur spécifié est incorrect.',
        'firebase.error.INVALID_USER': "Le compte utilisateur spécifié n'existe pas.",
        'footer.madeByHtml': 'Réalisé avec amour par',
        'intl.page.unreadCount': '{unreadCount, plural, one {message} other {messages}}',
        'loading.loadingText': 'Chargement',
        'loading.longLoadingText': "Chargement toujours, s'il vous plaît vérifier votre connexion",
        'notFound.continue': "Continuez ici s'il vous plaît.",
        'notFound.h1': "Cette page n'est pas disponible",
        'notFound.p': 'Le lien est peut-être périmé ou la page a été supprimée.',
        'todos.buttons.add100': 'Ajouter 100 tâches',
        'todos.buttons.clearAll': 'Tout supprimer',
        'todos.buttons.clearCompleted': 'Suppression terminée',
        'todos.leftTodos':
          "{leftTodos, plural, =0 {Il n'y a rien à faire, profitez ! :-)} one {Vous avez {leftTodos} tâche} other {Vous avez {leftTodos} tâches}}",
        'todos.newTodo.placeholder': "Qu'avez-vous à faire ?",
        'todos.todos.empty': "C'est plutôt calme par ici...",
      },
    },
  },
};
